version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            -   db


    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: hulk_apps
            MYSQL_USER: hulk_apps
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        volumes:
            -   ./storage/dbdata:/var/lib/mysql
        ports:
            -   33066:3306
